### ISSUE TITLE
爬虫改动，收集失效

### ISSUE THREAD

**Issue by godzeo** [wgpsec/ENScan#3]

**Comment by godzeo** [comment]
1、所有的银行的企业收集失效，应该是页面改动了
农业银行 招商银行等等
```
==== 【命令行模式】 请输入关键词 ====
农业银行
  0%|                                                                                    | 0/100 [00:00<?, ?it/s]2021-08-12 13:57:33,980 - INFO - 【开始查询关键词】 农业银行
【根据关键词查询到公司】 中国农业银行股份有限公司
28678123622427
Traceback (most recent call last):
  File "ENScan.py", line 699, in <module>
    Scan.main()
  File "ENScan.py", line 658, in main
    self.get_company_info(self.pid)
  File "ENScan.py", line 481, in get_company_info
    self.c_data['info'] = self.get_company_c(pid, True)
  File "ENScan.py", line 382, in get_company_c
    s_info = self.get_company_info_user(pid)
  File "ENScan.py", line 331, in get_company_info_user
    info["invest"] = item_detail['newTabs'][0 + l]['children'][7]['total']
IndexError: list index out of range
 10%|███████▌                                                                   | 10/100 [00:02<00:25,  3.58it/s]
```
![image](https://user-images.githubusercontent.com/64398024/129145840-849c126c-77bf-4e5a-8881-ba2c33e352cd.png)



2、测试小米的app信息也收集不到了

![image](https://user-images.githubusercontent.com/64398024/129145740-2719efc9-180b-4578-a13e-bd32419ad700.png)
